# Enable control-s and control-q
stty -ixon
# Remaping caps to escape
setxkbmap -option caps:escape

# Append history
setopt appendhistory

# If you come from bash you might have to change your $PATH.
# To allow for completion on base16_*
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# If "most" pager is installed, use it to have colored man pages!
if [ -x "$(command -v most)" ]; then
    export PAGER='most'
fi

# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

kitty + complete setup zsh | source /dev/stdin

# Always start into playground section
if [ -z "$TMUX" ]; then
    base_session='playground'
    # Create a new session if it doesn't exist
    tmux has-session -t $base_session || tmux new-session -d -s $base_session
    tmux attach-session -t $base_session
fi

export PATH="${PATH:+${PATH}:}/home/sarios/.fzf/bin"

eval "$(starship init zsh)"
# Set up amoizing starship prompt
source ~/.fzf/shell/key-bindings.zsh
source ~/.fzf/fzf-tabs/fzf-tab.plugin.zsh
source ~/dotfiles/zsh/aliases
source ~/dotfiles/fzf/fzf.zsh
source ~/dotfiles/forgit/forgit.plugin.zsh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/pulse/debs/usr/lib/x86_64-linux-gnu
