# Enable control-s and control-q
stty -ixon
# Remaping caps to escape
setxkbmap -option caps:escape

# If you come from bash you might have to change your $PATH.
# To allow for completion on base16_*
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

ZSH_THEME="agnoster"

# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

kitty + complete setup zsh | source /dev/stdin

# Always start into playground section
if [ -z "$TMUX" ]; then
    base_session='playground'
    # Create a new session if it doesn't exist
    tmux has-session -t $base_session || tmux new-session -d -s $base_session
    tmux attach-session -t $base_session
fi

prompt_end() {
    if [[ -n $CURRENT_BG ]]; then
        print -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
    else
        print -n "%{%k%}"
    fi

    print -n "%{%f%}"
    CURRENT_BG='' 

    #Adds the new line and ➜ as the start character.
    printf "\n ➜";
}


plugins=(
    git
    colored-man-pages
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source ~/dotfiles/zsh/aliases

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
